### ISSUE TITLE
test du module flexiadmin

### ISSUE THREAD

**Issue by rottenbergmichel** [micker/mod_flexiadmin#11]
Bonjour,

J'ai chargé la nouvelle version du mod_flexiadmin. 
Cette fois ci c'est bon. Il n'y a plus de message au chargement.

J'ai testé différentes options.

Toutes mes félicitations pour ce module.

J'ai utilisé l'onglet 'onglet personnalisé'. Sur ce point j'ai une suggestion : 
pour la création bouton d'ajout, est-il possible de ne pas mettre de catégorie mais simplement le type d'enregistrement : si on oblige une catégorie, on risque d'oublier de la modifier lors de la création. Si on ne met pas de catégorie, on ne peut  enregistrer l'article tant qu'il n'y a a pas de catégorie.

cordialement

Michel

**Comment by micker** [comment]
Hello nouvelle version et nouvelles fonctions
mais ta requette n'ai pas possible actuellement car j'utilise les class de flexicontent pure pour éviter tout conflict et le dev de flexi ne n'a pas prévu ce cas
désoler
mais avec les nouveaux boutons tu pourras outre passé cette limitation
