### ISSUE TITLE
fix bug Strings remove space and wrong

### ISSUE THREAD

**Issue by lungkao** [micker/mod_flexiadmin#20]
MOD_FLEXIADMIN="Module admin for FLEXIcontent"
FLEXI_ADMIN_DESC="Quick administration module for FLEXIcontent (use CPANEL position)"
FLEXI_ADMIN_INTRO="FLEXI ADMIN MODULE need to be publish in cpanel position. If you want to display in sidebar, choose sidebar template and choose icon position in Isis .Don't forget to <button class='btn btn'><a href='index.php?option=com_modules&filter_client_id=1&filter_module=mod_flexiadmin'>do it!</a></button>"
;;Admin
;;Main tab
FLEXI_ADMIN_DISPLAY_CONFIG_MODULE="Config module"
FLEXI_ADMIN_DISPLAY_CONFIG_MODULE_DESC="Display or hide configut=ration button in module"
FLEXI_ADMIN_NB_ITEM_DISPLAY="Displaying items"
FLEXI_ADMIN_NBITEM="Number of items"
FLEXI_ADMIN_NBITEM_DESC="Number of items displayed in the blocks"
FLEXI_ADMIN_COLUMN="Number of column"
FLEXI_ADMIN_COLUMN_DESC="Number of column for displaying blocks"
FLEXI_ADMIN_TABS="Displaying tabs"
FLEXI_ADMIN_TABS_CUSTOM="Custom tab"
FLEXI_ADMIN_TABS_CREATE="Create tab"
FLEXI_ADMIN_TABS_MANAGE="Manage tab"
FLEXI_ADMIN_TABS_ADMIN="Admin tab"
FLEXI_ADMIN_FREE_TAB="Free tab"
FLEXI_FREE_TABS_ADMIN="Free tab"
FLEXI_ADMIN_FREE_TAB_DESC="You can create free link to componant or module editing"
FLEXI_ADMIN_TABS_FREE_TAB_NAME="Other action"
FLEXI_ADMIN_BLOCK_DISPLAY="Displaying blocks"
FLEXI_ADMIN_DISPLAYBLOCK_PENDING="Block waiting"
FLEXI_ADMIN_DISPLAYBLOCK_PENDING_DESC="Display a list of items in the queue"
FLEXI_ADMIN_DISPLAYBLOCK_REVISED="Block revision"
FLEXI_ADMIN_DISPLAYBLOCK_REVISED_DESC="View the list of items under review"
FLEXI_ADMIN_DISPLAYBLOCK_INPROGRESS="Block in progress"
FLEXI_ADMIN_DISPLAYBLOCK_INPROGRESS_DESC="Display a list of items in progress"
FLEXI_ADMIN_DISPLAYBLOCK_DRAFT="Block draft"
FLEXI_ADMIN_DISPLAYBLOCK_DRAFT_DESC="View the list of draft articles"
FLEXI_ADMIN_DISPLAYBLOCK_YOURITEM="Block User"
FLEXI_ADMIN_DISPLAYBLOCK_YOURITEM_DESC="Display a list of items the user connected"
FLEXI_ADMIN_DISPLAYBLOCK_VERSION="Block Version"
FLEXI_ADMIN_DISPLAYBLOCK_VERSION_DESC="Display the version number FLEXIcontent"
FLEXI_ADMIN_BLOCKCUSTOM_DESC="Custom Blocks"
FLEXI_ADMIN_BLOCKCUSTOM1="Name of block 1"
FLEXI_ADMIN_BLOCKCUSTOM2="Name of block 2"
FLEXI_ADMIN_BLOCKCUSTOM3="Name of block 3"
FLEXI_ADMIN_BLOCKCUSTOM4="Name of block 4"
FLEXI_ADMIN_BLOCKCUSTOM5="Name of block 5"
FLEXI_ADMIN_BLOCKCUSTOM6="Name of block 6"
FLEXI_ADMIN_BLOCKCUSTOM7="Name of block 7"
FLEXI_ADMIN_BLOCKCUSTOM8="Name of block 8"
FLEXI_ADMIN_BLOCKCUSTOM9="Name of block 9"
FLEXI_ADMIN_BLOCKCUSTOM10="Name of block 10"
FLEXI_ADMIN_NAME_BUTTON="Button name"
FLEXI_ADMIN_NAME_BUTTON_DESC="Tipe name of button as you want to display"
FLEXI_ADMIN_TYPES="Auto Type"
FLEXI_ADMIN_TYPES_DESC="Select automatique type for this button"
FLEXI_ADMIN_CAT="Auto Categorie"
FLEXI_ADMIN_CAT_DESC="Select automatique categorie for this button"
FLEXI_ADMIN_SIDEBAR_OPTIONS="Sidebar option"
FLEXI_ADMIN_SIDEBAR_TABS_MOD="Tabs"
FLEXI_ADMIN_SIDEBAR_TABS_MOD_DESC="Display link in tabs or in list with title (same name of tab)"
FLEXI_ADMIN_DBUTTON1="Block 1"
FLEXI_ADMIN_DBUTTON2="Block 2"
FLEXI_ADMIN_DBUTTON3="Block 3"
FLEXI_ADMIN_DBUTTON4="Block 4"
FLEXI_ADMIN_DBUTTON5="Block 5"
FLEXI_ADMIN_DBUTTON6="Block 6"
FLEXI_ADMIN_DBUTTON7="Block 7"
FLEXI_ADMIN_DBUTTON8="Block 8"
FLEXI_ADMIN_DBUTTON9="Block 9"
FLEXI_ADMIN_DBUTTON10="Block 10"
FLEXI_ADMIN_BUTTON1="Button 1"
FLEXI_ADMIN_BUTTON2="Button 2"
FLEXI_ADMIN_BUTTON3="Button 3"
FLEXI_ADMIN_BUTTON4="Button 4"
FLEXI_ADMIN_BUTTON5="Button 5"
FLEXI_ADMIN_BUTTON6="Button 6"
FLEXI_ADMIN_BUTTON7="Button 7"
FLEXI_ADMIN_BUTTON8="Button 8"
FLEXI_ADMIN_BUTTON9="Button 9"
FLEXI_ADMIN_BUTTON10="Button 10"
FLEXI_ADMIN_BLOCKHEIGHT="Fixe height"
FLEXI_ADMIN_BLOCKHEIGHT_DESC="Force height of block ex 200PX. Adding scrolling inside blocks"

;;Custom tab
FLEXI_ADMIN_NAME_TAB="Tab name"
FLEXI_ADMIN_NAME_TAB_DESC="Tab name for custom tab"
FLEXI_ADMIN_CUSTOM_TAB="Custom tabs"
FLEXI_ADMIN_CUSTOM_TAB_DESC="You can add and remove button for your custom tab"
FLEXI_ADMIN_ITEM="Edit Item"
FLEXI_ADMIN_ITEM_DESC="Id of editing item"
FLEXI_ADMIN_BUTTON_ITEM_ADD="Custom ADD button"
FLEXI_ADMIN_BUTTON_ITEM_ADD1="Custom Add button 1"
FLEXI_ADMIN_BUTTON_ITEM_ADD2="Custom Add button 2"
FLEXI_ADMIN_BUTTON_ITEM_ADD3="Custom Add button 3"
FLEXI_ADMIN_BUTTON_ITEM_ADD4="Custom Add button 4"
FLEXI_ADMIN_BUTTON_ITEM_ADD5="Custom Add button 5"
FLEXI_ADMIN_BUTTON_ITEM_ADD6="Custom Add button 6"
FLEXI_ADMIN_BUTTON_ITEM_ADD7="Custom Add button 7"
FLEXI_ADMIN_BUTTON_ITEM_ADD8="Custom Add button 8"
FLEXI_ADMIN_BUTTON_ITEM_ADD9="Custom Add button 9"
FLEXI_ADMIN_BUTTON_ITEM_ADD10="Custom Add button 10"
FLEXI_ADMIN_CAT_FILTERING="Custom Categories button"
FLEXI_ADMIN_CAT_FILTERING1="Link to categorie 1"
FLEXI_ADMIN_CAT_FILTERING2="Link to categorie 2"
FLEXI_ADMIN_CAT_FILTERING3="Link to categorie 3"
FLEXI_ADMIN_CAT_FILTERING4="Link to categorie 4"
FLEXI_ADMIN_CAT_FILTERING5="Link to categorie 5"
FLEXI_ADMIN_CAT_FILTERING6="Link to categorie 6"
FLEXI_ADMIN_CAT_FILTERING7="Link to categorie 7"
FLEXI_ADMIN_CAT_FILTERING8="Link to categorie 8"
FLEXI_ADMIN_CAT_FILTERING9="Link to categorie 9"
FLEXI_ADMIN_CAT_FILTERING10="Link to categorie 10"
FLEXI_ADMIN_ITEM_EDIT="Custom editing item button"
FLEXI_ADMIN_ITEM_EDIT1="Link to item 1"
FLEXI_ADMIN_ITEM_EDIT2="Link to item 2"
FLEXI_ADMIN_ITEM_EDIT3="Link to item 3"
FLEXI_ADMIN_ITEM_EDIT4="Link to item 4"
FLEXI_ADMIN_ITEM_EDIT5="Link to item 5"
FLEXI_ADMIN_ITEM_EDIT6="Link to item 6"
FLEXI_ADMIN_ITEM_EDIT7="Link to item 7"
FLEXI_ADMIN_ITEM_EDIT8="Link to item 8"
FLEXI_ADMIN_ITEM_EDIT9="Link to item 9"
FLEXI_ADMIN_ITEM_EDIT10="Link to item 10"
FLEXI_ADMIN_CUSTOM_TAB_NAME="Custom Name"

;;Create tab
FLEXI_ADMIN_CREATION_TAB="Tab Create"
FLEXI_ADMIN_CREATION_TAB_DESC=""
FLEXI_ADMIN_DISPLAYBUTTON_ADDITEM="Add item button"
FLEXI_ADMIN_DISPLAYBUTTON_ADDITEM_DESC="Display or hide add item button in create tab"
FLEXI_ADMIN_DISPLAYBUTTON_ADDCATEGORY="Add category button"
FLEXI_ADMIN_DISPLAYBUTTON_ADDCATEGORY_DESC="Display or hide add category button in create tab"
FLEXI_ADMIN_DISPLAYBUTTON_ADDTAG="Add tag button"
FLEXI_ADMIN_DISPLAYBUTTON_ADDTAG_DESC="Display or hide add tag button in create tab"
FLEXI_ADMIN_DISPLAYBUTTON_ADDUSER="Add user button"
FLEXI_ADMIN_DISPLAYBUTTON_ADDUSER_DESC="Display or hide add user button in create tab"
FLEXI_ADMIN_DISPLAYBUTTON_ADDGROUP="Add group button"
FLEXI_ADMIN_DISPLAYBUTTON_ADDGROUP_DESC="Display or hide add group button in create tab"

;;Manage tab
FLEXI_ADMIN_GESTION_TAB="Tab Manage"
FLEXI_ADMIN_GESTION_TAB_DESC=""
FLEXI_ADMIN_DISPLAYBUTTON_MANAGEITEMS="Display Manage Items Button"
FLEXI_ADMIN_DISPLAYBUTTON_MANAGEITEMS_DESC="Display Manage Items Button"
FLEXI_ADMIN_DISPLAYBUTTON_BUTTONMANAGECATEGORIES="Display Manage Categories Button"
FLEXI_ADMIN_DISPLAYBUTTON_BUTTONMANAGECATEGORIES_DESC="Display Manage Categories Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGETYPES="Display Manage Types Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGETYPES_DESC="Display Manage Types Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGETAGS="Display Manage Tags Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGETAGS_DESC="Display Manage Tags Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEFIELDS="Display Manage Fields Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEFIELDS_DESC="Display Manage Fields Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEAUTHORS="Display Manage Authors Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEAUTHORS_DESC="Display Manage Authors Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEGROUPS="Display Manage Groups Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEGROUPS_DESC="Display Manage Groups Button"

;;Admin tab
FLEXI_ADMIN_ADMIN_TAB="Tab administration"
FLEXI_ADMIN_ADMIN_TAB_DESC=""
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONADDFIELDS="Add field button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONADDFIELDS_DESC="Display or hide add field button in admin tab"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONADDTYPES="Add type button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONADDTYPES_DESC="Display or hide add type button in admin tab"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONADMIN="FLEXIcontent config"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONADMIN_DESC="Display or hide config button in admin tab"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEFILES="Display Manage Files Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONMANAGEFILES_DESC="Display Manage Files Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONIMPORTCONTENT="Display Import Content Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONIMPORTCONTENT_DESC="Display Import Content Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONSTATS="Display Stats Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONSTATS_DESC="Display Stats Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONINDEX="Display Index Button"
FLEXI_ADMIN_DISPLAYBUTTON_HIDDEBUTTONINDEX_DESC="Display Index Button"

;;Free tab
FLEXI_ADMIN_FREE_BUTTON_ITEM_1="Free button 1"
FLEXI_ADMIN_FREE_BUTTON_ITEM_2="Free button 2"
FLEXI_ADMIN_FREE_BUTTON_ITEM_3="Free button 3"
FLEXI_ADMIN_FREE_BUTTON_ITEM_4="Free button 4"
FLEXI_ADMIN_FREE_BUTTON_ITEM_5="Free button 5"
FLEXI_ADMIN_FREE_BUTTON_ITEM_6="Free button 6"
FLEXI_ADMIN_FREE_BUTTON_ITEM_7="Free button 7"
FLEXI_ADMIN_FREE_BUTTON_ITEM_8="Free button 8"
FLEXI_ADMIN_FREE_BUTTON_ITEM_9="Free button 9"
FLEXI_ADMIN_FREE_BUTTON_ITEM_10="Free button 10"
FLEXI_ADMIN_FREE_NAME_BUTTON="Free name button"
FLEXI_ADMIN_FREE_LINK="Free link"
FLEXI_ADMIN_ICON="Free icon"
FLEXI_ADMIN_FREE_TAB_NAME="Other action"
FLEXI_ADMIN_FREE_TAB_NAME_2="Name of tab"
FLEXI_ADMIN_FREE_TAB_NAME_2_DESC="Tip name of tab, empty this field to default value"

;;display
FLEXI_ADMIN_TAB_CREATE_D="Create"
FLEXI_ADMIN_TAB_MANAGE_D="Manage"
FLEXI_ADMIN_TAB_ADMIN_D="Admin"
FLEXI_TRASHED="Trashed"
FLEXI_ADMIN_CUSTOM_TAB_NAME="Custom tab"
FLEXI_ADMIN_ITEM="Management of items"
FLEXI_ADMIN_ADDITEM="Add item"
FLEXI_ADMIN_CATLIST="Management of categories"
FLEXI_ADMIN_ADDCATLIST="Add category"
FLEXI_ADMIN_TYPELIST="Management of type"
FLEXI_ADMIN_ADDTYPE="Add type"
FLEXI_ADMIN_TAGLIST="Management of tags"
FLEXI_ADMIN_ADDTAG="Add tag"
FLEXI_ADMIN_FIELDLIST="Management of fields"
FLEXI_ADMIN_ADDFIELD="Add field"
FLEXI_ADMIN_AUTHORLIST="Management of authors"
FLEXI_ADMIN_ADDAUTHOR="Add author"
FLEXI_ADMIN_GROUPSLIST="group management"
FLEXI_ADMIN_ADDGROUPS="Add group"
FLEXI_ADMIN_FILEMANAGER="Management of files"
FLEXI_ADMIN_IMPORT="Import Content"
FLEXI_ADMIN_STATS="Statistics"
FLEXI_ADMIN_SEARCH="Indexing"
FLEXI_ADMIN_ALL="All"
FLEXI_ADMIN_REVISED="Article review"
FLEXI_ADMIN_PENDING="Article waiting"
FLEXI_ADMIN_INPROGRESS="Article in progress"
FLEXI_ADMIN_DRAFT="Article in draft"
FLEXI_YOUR_ITEM="Your articles"
FLEXI_ADMIN_GEN="FLEXIcontent Admin"
FLEXI_ADMIN_DISPLAYBLOCK_TRASHED="Display Trashed"
FLEXI_ADMIN_ADDCATEGORY="Add category"
FLEXI_ADMIN_ITEMLIST="Management of items"
FLEXI_ADMIN_TRASHED="Article trashed"
FLEXI_IN_PROGRESS="in progress"
FLEXI_PUBLISHED="published"
FLEXI_ADMIN_CREATED_BY="Created by"
FLEXI_ADMIN_MODIFIED_BY="Modified by"
FLEXI_UNPUBLISHED="unpublished"
FLEXI_ARCHIVED="archived"
FLEXI_PENDING="pending"
FLEXI_DRAFT="draft"

![2015-04-18_08-36-58](https://cloud.githubusercontent.com/assets/2047778/7213390/a184a0b2-e5a6-11e4-9579-88a2c416d116.jpg)
![2015-04-18_08-35-06](https://cloud.githubusercontent.com/assets/2047778/7213391/a30c68fc-e5a6-11e4-9bf5-7d7bd29ec37c.jpg)

**Comment by micker** [comment]
thanks
