### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by iamrobert** [micker/mod_flexiadmin#21]
Hi Micker,

If you don't have extra fields displaying - it gives the following php notice:

![token administration control panel](https://cloud.githubusercontent.com/assets/8617673/9709131/2628cb9c-5558-11e5-9979-791258a2fb40.png)

If you wrap them in: if(isset($extrafield)) {  
````
	if(isset($extrafield)) { 
						foreach ($extraFieldlist1 as $extrafield){
							FlexicontentFields::getFieldDisplay($item, $extrafield);
							$value= $item->fields[$extrafield]->display;
							echo '<td>';
							echo $value;
							echo '</td>';
						}
						}

The error goes away - but not sure if it works for $extrafield examples.

**Comment by micker** [comment]
thanks for return its only a notice change reporting in your site
i work on it to kill it and add display field like categorie and statue
will commit
reagrds
