### ISSUE TITLE
Old version number still exists for 0.9.0

### ISSUE THREAD

**Issue by othbert** [micker/mod_flexiadmin#26]
Hi, thanks for the module. Just a quick issue with the version number for 0.9.0 release.

It is still set to 0.8.0, causing Joomla to "helpfully" throw up a message saying there are updates:
"1 Extension Update(s) are available: View Updates"

Cheers

**Comment by micker** [comment]
sorry but where ?

**Comment by othbert** [comment]
My bad; I pulled from releases not the current source.

Went to https://github.com/micker/mod_flexiadmin/releases
Pulled from https://github.com/micker/mod_flexiadmin/releases/tag/0.9

The naming of "FLEXI googlemap module v0.9N" threw me off, I see that it is the newest version though. I will use that.

(Incidentally, that zip is 0.9.1 but the xml states 0.9.0) :grin:

**Comment by micker** [comment]
thanks for return
