### ISSUE TITLE
lien vers items personne courante

### ISSUE THREAD

**Issue by web54** [micker/mod_flexiadmin#36]
Il faudrait trouver le moyen de faire comme dans le lien my items en front pour filtrer vers les éléments de la personne connectée en backend.

**Comment by micker** [comment]
hello ta un block pour ca (utilisateur connecter)
tu voudrais avoir un argument dans la generation des boutons ?

**Comment by micker** [comment]
adding here
https://github.com/micker/mod_flexiadmin/commit/f134b05d099aa9b1612acc10468b81a014d0d459
