### ISSUE TITLE
avoir la bibilothèque font awesome en local

### ISSUE THREAD

**Issue by web54** [micker/mod_flexiadmin#37]
le module est fortement utilisé pour des applications intranet et/ ou extranet
Peut on faire en sorte de charger la bibliothèque Font awesome et quel serait le fichier à modifier pour pointer vers cette bibliothèque quand on est hors ligne (intranet) ?

**Comment by micker** [comment]
il faut que je check ca pour avoir une option de choix

**Comment by web54** [comment]
si pas trop compliqué je peux aider



	

Le 03/12/2020 à 09:34, Berges Yannick a écrit :

**Comment by micker** [comment]
prévu dans la prochaine version
