### ISSUE TITLE
POPOVERS Failing

### ISSUE THREAD

**Issue by iamrobert** [micker/mod_flexiadmin#38]
When looking at the editor - the popovers don't seem to work:

![](https://i.imgur.com/UrWNptH.png)

If I apply the following it seems usable as a temporary fix:

```
.rl-admin-popover {
display: none !important;
}
```

**Comment by micker** [comment]
Hello on last version (2.9) and in joomla 4.X ?

**Comment by iamrobert** [comment]
Hi @micker 

Isn't the latest version [2.6](https://github.com/micker/mod_flexiadmin/blob/v2/mod_flexiadmin.xml)?

I don't see the 2.9 branch. 

Also - the icon finder tool isn't working for me:

https://youtu.be/1KheCrboprM

Joomla 4.3.3

**Comment by micker** [comment]
yes i am agree mistake lastest version in 2.6 but i couldn't reproduce it ... i will search more
=> i will prepare a new module version:
- less code
- more flexible (no more limitation with order)
- local icon
- better icon script with jquery

**Comment by iamrobert** [comment]
@micker 

I've investigated further. The popover is related to advanced to [Advanced Module Manager](https://regularlabs.com/advancedmodulemanager). 

If I load it through the default com_modules - it works.

But - I can't solve the icon finder tool.

From my research - it only works if you put this code under the body or load it window onload like this:


```                      window.onload = function() {
                        var element = document.createElement("script");
                        element.src = "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-iconpicker/1.9.0/js/bootstrap-iconpicker.min.js";
                        document.body.appendChild(element);
                    };```  
                    
                 But I can't get it to work with your JS code.

**Comment by micker** [comment]
its only work after save module (you add 1 value, save and after it will works) did you test it ?

**Comment by iamrobert** [comment]
@micker 

Here's the steps I'm following 
https://youtu.be/D3F-yXllPSo

Perhaps there is something wrong with my setup? 

Its working now.

**Comment by iamrobert** [comment]
Wait it seems to work! On the 7th try

**Comment by micker** [comment]
ah ???
in you video i think you have an js in console error => check if js file ar create in media/mod_flexiadmin
in my dev site and some prod site all seems good
very strange
