### ISSUE TITLE
Problème FontAwesome

### ISSUE THREAD

**Issue by AlainRnet** [micker/mod_flexiadmin#41]
Le CSS fait référence à des fichiers dans le dossier fonts qui ne sont pas présents :
https://github.com/micker/mod_flexiadmin/blob/f1cb829a651fc404694d8ceea5a565f0d9431a30/media/css/font-awesome.min.css#L4
Dans la gestion du module, le choix des icônes n'affiche aucun icône, quelque soit la collection choisie (Solid, Regular, Brands).

Question subsidiaire : pourquoi ne pas prendre les fonts du template Atum dans media/vendor/fontawesome-free/webfonts ?

**Comment by micker** [comment]
hello merci du retour je vais regarder cela
je ne prend pas les font de joomla car on a plus de choix via ce script

**Comment by micker** [comment]
tu essayer avec cette modification ?
https://github.com/micker/mod_flexiadmin/commit/cf2a33ee6439c9f053d813f20e5d465f7a88cf89
Merci

**Comment by AlainRnet** [comment]
C'est parfait. Merci.
